version: '2'
services:
  python-ao:
    build: ./python-ao/
    environment:
      - APPOPTICS_SERVICE_KEY=${APPOPTICS_SERVICE_KEY}:python-ao
    ports:
      - "5000:5000"
  node-ao:
    build: ./node-ao/
    environment:
      - APPOPTICS_SERVICE_KEY=${APPOPTICS_SERVICE_KEY}:node-ao
    ports:
      - "3000:3000"
  golang-ao:
    build: ./golang-ao/
    environment:
      - APPOPTICS_SERVICE_KEY=${APPOPTICS_SERVICE_KEY}:golang-ao
    ports:
      - "8000:8000"
  redis:
    image: redis
    ports:
      - "6379:6379"
